# Generated by Django 3.2.6 on 2021-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.CharField(max_length=100, null=True, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='pies_basket',
            field=models.ManyToManyField(blank=True, related_name='basket_pies', to='pies_app.Pies', verbose_name='Тортики в корзине'),
        ),
    ]
