# Generated by Django 3.2.6 on 2021-09-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pies_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pies_order',
        ),
        migrations.AddField(
            model_name='order',
            name='pies_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pies_id_fk', to='pies_app.pies', verbose_name='Pies'),
        ),
    ]
