# Generated by Django 3.2.6 on 2021-09-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies_app', '0002_auto_20210902_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_type',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ находится в обработке'), ('is_ready', 'Заказ готов'), ('completed', 'Заказ получен')], max_length=100, null=True, verbose_name='статус доставки'),
        ),
    ]
