# Generated by Django 3.2.6 on 2021-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies_app', '0002_auto_20210916_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buying_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_type',
        ),
        migrations.AddField(
            model_name='order',
            name='buying',
            field=models.CharField(choices=[('s', 'Самовывоз'), ('d', 'Доставка')], default='n', max_length=100, null=True, verbose_name='Статус доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'Новый заказ'), ('in', 'Заказ находится в обработке'), ('is', 'Заказ готов'), ('c', 'Заказ получен')], max_length=100, null=True, verbose_name='Статус заказа'),
        ),
    ]
