# Generated by Django 3.2.6 on 2021-09-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pies_app', '0003_order_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket', to='pies_app.basket', verbose_name='корзина'),
        ),
    ]
