# Generated by Django 3.2.6 on 2021-09-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pies_app', '0005_remove_order_pies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
