# Generated by Django 3.2.6 on 2021-09-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pies_app', '0006_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pies',
            name='information_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
